update README to reflect cronjob changes
aodn/data-services pull request #1086
Opened 2022-03-23 04:34 UTC by digorgonzola

2022-03-23 05:22 UTC, akashisama requested changes

2022-03-23 05:26 UTC, akashisama commented
Will we need to be careful about the promotion order of this vs the changes in chef (https://github.com/aodn/chef/pull/1182/files)?

2022-03-23 05:59 UTC, mhidas reviewed
Just a few suggestions

2022-03-23 05:59 UTC, mhidas commented on README.md
> +| $PYTHONPATH | $DATA_SERVICES_DIR/lib/python | Location of data-services python interpreter |
There is no python interpreter there - AFAIK these scripts usually run on the system python!
```suggestion
| $PYTHONPATH | $DATA_SERVICES_DIR/lib/python | Location of data-services python scripts/modules |
```

2022-03-23 05:59 UTC, mhidas commented on README.md
> +| $DATA_SERVICES_TMP_DIR | nil | |
```suggestion
| $DATA_SERVICES_TMP_DIR | /mnt/ebs/tmp | Temp dir for data services work (not on root partition like /tmp) |
```

2022-03-23 05:59 UTC, mhidas commented on README.md
> +| $ERROR_DIR | /mnt/ebs/error |Errors |
```suggestion
| $ERROR_DIR | /mnt/ebs/error | Dir. to store incoming files that cause pipeline errors |
```

2022-03-24 00:53 UTC, akashisama approved these changes

2022-03-24 00:53 UTC, merged