S3 listing of object versions and download options
aodn/data-services pull request #1136
Opened 2023-01-18 02:47 UTC by bpasquer

this is my take on the S3 listing and download of previous versions

2023-01-18 05:53 UTC, lbesnard requested changes

2023-01-18 05:53 UTC, lbesnard commented on lib/python/s3_ls_prefix.py
> +    parser.add_argument("-v", "--versionid", nargs=2 ,
I believe nargs should be =1

2023-01-18 05:53 UTC, lbesnard commented on lib/python/s3_ls_prefix.py
> +   ./s3_ls_prefix.py -l CSIRO/Climatology/Ocean_Acidification/OA_Reconstruction.nc
indent

2023-01-18 05:53 UTC, lbesnard commented on lib/python/s3_ls_prefix.py
> +    s3.download_file(bucket, prefix, filename, ExtraArgs={'VersionId': versionid})
the -o option for output folder is not used anymore

2023-02-23 03:52 UTC, bpasquer commented
Instead of using this python script, it's been requested that awcli is installed in prod, as it is providing a range of functionalities to access S3 version information.
see comments https://github.com/aodn/issues/issues/1321

Closing

2023-02-23 03:52 UTC, closed without merging